project:
  type: website
  output-dir: docs
website:
  title: "cadevanek.github.io "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - resume.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full
    fontcolor: "#8d47b8"
editor: visual

