---
title: "resume"
format: html
---

cadevanek@gmail.com  | 512-851-3437 | Fort Collins, CO | linkedin.com/in/cadevanek

About Me

I am a student studying ecosystem and sustainability science. I have always been passionate about sustainability and ecology, and hope to help bridge the gaps between the natural world and the built environment. I value cooperation, collaboration, and empathy in a professional environment, and thrive as part of a goal-oriented team.

Education

Currently enrolled at Colorado State University, studying ecosystem and sustainability science, with an anticipated graduation year of 2026.

Professional Experience

Crew Member, Cheba Hut — 2023-Current
Works with a small team to provide quality food, service, sanitation, and equipment maintenance for a small sandwich shop.

Front Desk, Comfort Inn — 2023
Booked reservations, greeted guests, managed housekeeping, washed and folded laundry, as well as independently maintained general cleanliness of lobby and pool, etc.

Personal Skills

General laboratory experience
Management and monitoring of natural systems, such as terrariums and aquariums.
Computer Science Skills
Programming in Java, C, and Python
Data structures and file management
maintenance and observation of on-campus beehives as part of the apiculture club.
